configserver: true
bus: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}
  client:
    serviceUrl:
      defaultZone: https://apm-cloud-eureka-server-dev.grc-apps.svc.ice.ge.com/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: https://apm-cloud-eureka-server-dev.grc-apps.svc.ice.ge.com
    nonSecurePort: 80
